# COMANDOS PARA A AÇÃO 2:

# version: '3.8'
# services:
#   git-config:
#     image: ubuntu:latest
#     secrets:
#       - git_token
#     command: >
#       bash -c "apt-get update && apt-get install -y git &&
#       git config --global user.name 'My Git User' &&
#       git config --global user.token $(cat /run/secrets/git_token)"
# secrets:
#   git_token:
#     external: true


# COMANDOS PARA A AÇÃO 3:

version: '3.8'
services:
  app:
    image: imagem-teste-seguro
    networks:
      secure_internal_network:
        aliases:
          - secure-app
    command: tail -f /dev/null

networks:
  secure_internal_network:
    external: true